## Australia locality to arabic

In [13]:
import pandas as pd
from transformers import MarianTokenizer, MarianMTModel
from typing import List

In [ ]:
src = 'en'
trg = 'fr'

mname = f'Helsinki-NLP/opus-mt-{src}-{trg}'
model = MarianMTModel.from_pretrained(mname)
tok = MarianTokenizer.from_pretrained(mname)

In [3]:
tok.supported_language_codes

[]

In [ ]:
sample_text = "Total cases of Covid 19 by continent ,play with me,"
batch = tok.prepare_translation_batch(src_texts = [sample_text])
gen = model.generate(**batch)
words: List[str] = tok.batch_decode(gen, skip_special_tokens=True)
words

In [ ]:
words = tok.batch_decode(gen, skip_special_tokens=True)
words

In [6]:
words

['Nombre total de cas de Covid 19 par continent, jouer avec moi,']

In [173]:

def get_model(src_lang,trg_lang):
    src = src_lang
    trg = trg_lang
    
    mname = f'Helsinki-NLP/opus-mt-{src}-{trg}'
    model = MarianMTModel.from_pretrained(mname)
    tok = MarianTokenizer.from_pretrained(mname)
    return model,tok

def translate(model,tok,src_text):
    batch = tok.prepare_translation_batch(src_texts = [src_text])
    gen = model.generate(**batch)
    words: List[str]= tok.batch_decode(gen,  skip_special_tokens=True)
    return words

In [9]:
model,tok = get_model('en','fr')

In [178]:
word1 = translate(model,tok,["Do you want to play with me?", "say hey","what are you"])
word1

["['Veux-tu jouer avec moi?', 'dis bonjour', 'Qu'est-ce que tu es']"]

In [ ]:
MarianTokenizer.supported_language_codes

In [88]:
lang_codes = pd.read_csv('./data/language_codes.csv')
#lang_codes = lang_codes.filter(['Alpha3b_Code','Alpha2_Code','English_Name'])
lang_codes

,Alpha3b_Code,Alpha3t_Code,Alpha2_Code,English_Name,French_Name
0,aar,NaN,aa,Afar,afar
1,abk,NaN,ab,Abkhazian,abkhaze
2,ace,NaN,NaN,Achinese,aceh
3,ach,NaN,NaN,Acoli,acoli
4,ada,NaN,NaN,Adangme,adangme
...,...,...,...,...,...
481,znd,NaN,NaN,Zande languages,"zandÃ©, langues"
482,zul,NaN,zu,Zulu,zoulou
483,zun,NaN,NaN,Zuni,zuni
484,zxx,NaN,NaN,No linguistic content; Not applicable,pas de contenu linguistique; non applicable
485,zza,NaN,NaN,Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki,zaza; dimili; dimli; kirdki; kirmanjki; zazaki

In [89]:
#lng_codes = lang_codes.dropna()
lng_codes = lang_codes
lng_codes

,Alpha3b_Code,Alpha3t_Code,Alpha2_Code,English_Name,French_Name
0,aar,NaN,aa,Afar,afar
1,abk,NaN,ab,Abkhazian,abkhaze
2,ace,NaN,NaN,Achinese,aceh
3,ach,NaN,NaN,Acoli,acoli
4,ada,NaN,NaN,Adangme,adangme
...,...,...,...,...,...
481,znd,NaN,NaN,Zande languages,"zandÃ©, langues"
482,zul,NaN,zu,Zulu,zoulou
483,zun,NaN,NaN,Zuni,zuni
484,zxx,NaN,NaN,No linguistic content; Not applicable,pas de contenu linguistique; non applicable
485,zza,NaN,NaN,Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki,zaza; dimili; dimli; kirdki; kirmanjki; zazaki

In [103]:
lang_codes[lang_codes['Alpha3b_Code']=='bem']

   Alpha3b_Code Alpha3t_Code Alpha2_Code English_Name French_Name
48          bem          NaN         NaN        Bemba       bemba

In [91]:
#English to other language supported
lang_supported = [
    'en','af','bcl','bem','ber','bg','br',
    'af','bi','bzs','ca','ceb','chk','crs','cs',
    'cy', 'da', 'de', 'ee','efi','el'
    'eo','et','eu','fi','fj','fr','ga',
    'gaa','gil','gl','guw','gv','ha','he',
    'hil','ho','ht','hu','id','ig','ilo',
    'is','iso','it','jap','kg','kj','kqn',
    'kwn','kwy','lg','ln','loz','lu','lua','lue',
    'lun','luo','lus','mfe','mg','mh','mk','ml',
    'mos','mr','mt','ng','niu','nl','nso','ny',
    'nyk','om','pag','pap','pis','pon','rnd','ro','ru','run',
    'rw','sg','sk','sm','sn','sq','ss',
    'st','sv','sw','swc','tdt','ti','tiv',
    'tl','tll','tn','to','toi','tpi','ts','tvl',
    'tw','ty','uk','umb','xh' 
]

In [108]:
str(lang_codes[(lang_codes['Alpha2_Code']=='ceb') | (lang_codes['Alpha3b_Code']=='ceb')]['English_Name'])[1:20].split(' '

['2', '', '', '', 'Cebuano\nName:', '']

In [104]:
#Creating a dictionary of supported lang_code:language 
lang_dic = {i:str(lang_codes[(lang_codes['Alpha2_Code']==i) | (lang_codes['Alpha3b_Code']==i)]['English_Name'])[6:25].split('\n')[0] for i in lang_supported}
lang_dic

{'en': ' English',
 'af': 'frikaans',
 'bcl': '([], Name: English_',
 'bem': 'Bemba',
 'ber': 'Berber languages',
 'bg': 'Bulgarian',
 'br': 'Breton',
 'bi': 'Bislama',
 'bzs': '([], Name: English_',
 'ca': 'Catalan; Valencian',
 'ceb': 'Cebuano',
 'chk': 'Chuukese',
 'crs': '([], Name: English_',
 'cs': ' Czech',
 'cy': ' Welsh',
 'da': ' Danish',
 'de': ' German',
 'ee': ' Ewe',
 'efi': ' Efik',
 'eleo': '([], Name: English_',
 'et': ' Estonian',
 'eu': 'Basque',
 'fi': ' Finnish',
 'fj': ' Fijian',
 'fr': ' French',
 'ga': ' Irish',
 'gaa': ' Ga',
 'gil': ' Gilbertese',
 'gl': ' Galician',
 'guw': '([], Name: English_',
 'gv': ' Manx',
 'ha': ' Hausa',
 'he': ' Hebrew',
 'hil': ' Hiligaynon',
 'ho': ' Hiri Motu',
 'ht': ' Haitian; Haitian C',
 'hu': ' Hungarian',
 'id': ' Indonesian',
 'ig': ' Igbo',
 'ilo': ' Iloko',
 'is': ' Icelandic',
 'iso': '([], Name: English_',
 'it': ' Italian',
 'jap': '([], Name: English_',
 'kg': ' Kongo',
 'kj': ' Kuanyama; Kwanyama',
 'kqn': '([], Name: English_',
 'kwn': '([], Name: English_',
 'kwy': '([], Name: English_',
 'lg': ' Ganda',
 'ln': ' Lingala',
 'loz': ' Lozi',
 'lu': ' Luba-Katanga',
 'lua': ' Luba-Lulua',
 'lue': '([], Name: English_',
 'lun': ' Lunda',
 'luo': ' Luo (Kenya and Tan',
 'lus': ' Lushai',
 'mfe': '([], Name: English_',
 'mg': ' Malagasy',
 'mh': ' Marshallese',
 'mk': ' Macedonian',
 'ml': ' Malayalam',
 'mos': ' Mossi',
 'mr': ' Marathi',
 'mt': ' Maltese',
 'ng': ' Ndonga',
 'niu': ' Niuean',
 'nl': ' Dutch; Flemish',
 'nso': ' Pedi; Sepedi; Nort',
 'ny': ' Chichewa; Chewa; N',
 'nyk': '([], Name: English_',
 'om': ' Oromo',
 'pag': ' Pangasinan',
 'pap': ' Papiamento',
 'pis': '([], Name: English_',
 'pon': ' Pohnpeian',
 'rnd': '([], Name: English_',
 'ro': ' Romanian; Moldavia',
 'ru': ' Russian',
 'run': ' Rundi',
 'rw': ' Kinyarwanda',
 'sg': ' Sango',
 'sk': ' Slovak',
 'sm': ' Samoan',
 'sn': ' Shona',
 'sq': 'Albanian',
 'ss': ' Swati',
 'st': ' Sotho, Southern',
 'sv': ' Swedish',
 'sw': ' Swahili',
 'swc': '([], Name: English_',
 'tdt': '([], Name: English_',
 'ti': ' Tigrinya',
 'tiv': ' Tiv',
 'tl': ' Tagalog',
 'tll': '([], Name: English_',
 'tn': ' Tswana',
 'to': ' Tonga (Tonga Islan',
 'toi': '([], Name: English_',
 'tpi': ' Tok Pisin',
 'ts': ' Tsonga',
 'tvl': ' Tuvalu',
 'tw': ' Twi',
 'ty': ' Tahitian',
 'uk': ' Ukrainian',
 'umb': ' Umbundu',
 'xh': ' Xhosa'}

## Dynamically get supported languages (English to other language support)

In [147]:

from transformers.hf_api import HfApi
model_list = HfApi().model_list()
org = "Helsinki-NLP/opus-mt-en"
model_ids = [x.modelId for x in model_list if x.modelId.startswith(org)]
suffix = [x.split('-')[4] for x in model_ids]
multi_models = [f'{org}/{s}' for s in suffix if s != s.lower()]
suffix

['CELTIC',
 'ROMANCE',
 'af',
 'bcl',
 'bem',
 'ber',
 'bg',
 'bi',
 'bzs',
 'ca',
 'ceb',
 'chk',
 'crs',
 'cs',
 'cy',
 'da',
 'de',
 'ee',
 'efi',
 'el',
 'eo',
 'et',
 'eu',
 'fi',
 'fj',
 'fr',
 'ga',
 'gaa',
 'gil',
 'gl',
 'guw',
 'gv',
 'ha',
 'he',
 'hil',
 'ho',
 'ht',
 'hu',
 'id',
 'ig',
 'ilo',
 'is',
 'iso',
 'it',
 'jap',
 'kg',
 'kj',
 'kqn',
 'kwn',
 'kwy',
 'lg',
 'ln',
 'loz',
 'lu',
 'lua',
 'lue',
 'lun',
 'luo',
 'lus',
 'mfe',
 'mg',
 'mh',
 'mk',
 'ml',
 'mos',
 'mr',
 'mt',
 'ng',
 'niu',
 'nl',
 'nso',
 'ny',
 'nyk',
 'om',
 'pag',
 'pap',
 'pis',
 'pon',
 'rnd',
 'ro',
 'ru',
 'run',
 'rw',
 'sg',
 'sk',
 'sm',
 'sn',
 'sq',
 'ss',
 'st',
 'sv',
 'sw',
 'swc',
 'tdt',
 'ti',
 'tiv',
 'tl',
 'tll',
 'tn',
 'to',
 'toi',
 'tpi',
 'ts',
 'tvl',
 'tw',
 'ty',
 'uk',
 'umb',
 'xh',
 'en_el_es_fi']

In [157]:

#suffix
#Creating a dictionary of supported lang_code:language 
lang_dic = {i:str(lang_codes[(lang_codes['Alpha2_Code']==i) | (lang_codes['Alpha3b_Code']==i)]['English_Name'])[7:22].split('\n')[0] for i in suffix}
lang_dic.values()

dict_values(['[], Name: Engli', '[], Name: Engli', 'rikaans', '[], Name: Engli', 'emba', 'erber languages', 'ulgarian', 'islama', '[], Name: Engli', 'atalan; Valenci', 'ebuano', 'huukese', '[], Name: Engli', 'Czech', 'Welsh', 'Danish', 'German', 'Ewe', 'Efik', 'Greek, Modern (', 'Esperanto', 'Estonian', 'asque', 'Finnish', 'Fijian', 'French', 'Irish', 'Ga', 'Gilbertese', 'Galician', '[], Name: Engli', 'Manx', 'Hausa', 'Hebrew', 'Hiligaynon', 'Hiri Motu', 'Haitian; Haitia', 'Hungarian', 'Indonesian', 'Igbo', 'Iloko', 'Icelandic', '[], Name: Engli', 'Italian', '[], Name: Engli', 'Kongo', 'Kuanyama; Kwany', '[], Name: Engli', '[], Name: Engli', '[], Name: Engli', 'Ganda', 'Lingala', 'Lozi', 'Luba-Katanga', 'Luba-Lulua', '[], Name: Engli', 'Lunda', 'Luo (Kenya and ', 'Lushai', '[], Name: Engli', 'Malagasy', 'Marshallese', 'Macedonian', 'Malayalam', 'Mossi', 'Marathi', 'Maltese', 'Ndonga', 'Niuean', 'Dutch; Flemish', 'Pedi; Sepedi; N', 'Chichewa; Chewa', '[], Name: Engli', 'Oromo', 'Pangasinan', 'Papiamento', '[], Name: Engli', 'Pohnpeian', '[], Name: Engli', 'Romanian; Molda', 'Russian', 'Rundi', 'Kinyarwanda', 'Sango', 'Slovak', 'Samoan', 'Shona', 'lbanian', 'Swati', 'Sotho, Southern', 'Swedish', 'Swahili', '[], Name: Engli', '[], Name: Engli', 'Tigrinya', 'Tiv', 'Tagalog', '[], Name: Engli', 'Tswana', 'Tonga (Tonga Is', '[], Name: Engli', 'Tok Pisin', 'Tsonga', 'Tuvalu', 'Twi', 'Tahitian', 'Ukrainian', 'Umbundu', 'Xhosa', '[], Name: Engli'])

In [161]:
lang_dic.keys()

dict_keys(['CELTIC', 'ROMANCE', 'af', 'bcl', 'bem', 'ber', 'bg', 'bi', 'bzs', 'ca', 'ceb', 'chk', 'crs', 'cs', 'cy', 'da', 'de', 'ee', 'efi', 'el', 'eo', 'et', 'eu', 'fi', 'fj', 'fr', 'ga', 'gaa', 'gil', 'gl', 'guw', 'gv', 'ha', 'he', 'hil', 'ho', 'ht', 'hu', 'id', 'ig', 'ilo', 'is', 'iso', 'it', 'jap', 'kg', 'kj', 'kqn', 'kwn', 'kwy', 'lg', 'ln', 'loz', 'lu', 'lua', 'lue', 'lun', 'luo', 'lus', 'mfe', 'mg', 'mh', 'mk', 'ml', 'mos', 'mr', 'mt', 'ng', 'niu', 'nl', 'nso', 'ny', 'nyk', 'om', 'pag', 'pap', 'pis', 'pon', 'rnd', 'ro', 'ru', 'run', 'rw', 'sg', 'sk', 'sm', 'sn', 'sq', 'ss', 'st', 'sv', 'sw', 'swc', 'tdt', 'ti', 'tiv', 'tl', 'tll', 'tn', 'to', 'toi', 'tpi', 'ts', 'tvl', 'tw', 'ty', 'uk', 'umb', 'xh', 'en_el_es_fi'])